### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by AlexPl292** [jonathanlermitage/intellij-extra-icons-plugin#68]
Hi, thank you for the great plugin!
I have a large project with a lot of modules and opened branches of the tries. Also, this project has a lot of facets. I've noticed that I see a pretty visible glitches in the project tree. After a small (and not really deep) investigation, I've found that you're collecting all the facts of all the modules on each icon resolution. That seems not very effective at first glance, so maybe you could cache the list of the facets? This is especially interesting because, as far as I understand, there are no default rules that use facets, so they aren't actually used in most cases.
Also, the double `for` inside of `lermitage.intellij.extra.icons.ModelCondition#check` also seems a little bit slow, so maybe you could just collect the names of facets in small letters and use the power of set?

Thank you in advance!

**Comment by jonathanlermitage** [comment]
Thx! 
Excellent idea, I will implement these improvements.

**Comment by jonathanlermitage** [comment]
It should be fixed now. Can you please make a try with attached plugin file? Thx! @AlexPl292 
[Extra Icons-1.61.0.203.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/7131797/Extra.Icons-1.61.0.203.zip)

**Comment by AlexPl292** [comment]
Oh, yeah, this seems to be better. I still see some glitches, but they seem to be a platform issue (since it's reproduced with the disabled plugin). Anyway, YourKit shows a nice improvement :)
Also, in case you're looking for the way of this cache invalidation, `com.intellij.facet.ProjectFacetListener` should help you.

Thank you for the update!

**Comment by jonathanlermitage** [comment]
Thx!
